apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-pvc
spec:
  storageClassName: ""
  volumeName: audit-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi